package com.daboerp.gestion.domain.valueobject;

public enum Nationality {
    // Latin America
    COLOMBIA,
    MEXICO,
    ARGENTINA,
    BRAZIL,
    CHILE,
    PERU,
    VENEZUELA,
    ECUADOR,
    BOLIVIA,
    PARAGUAY,
    URUGUAY,
    PANAMA,
    COSTA_RICA,
    GUATEMALA,
    HONDURAS,
    EL_SALVADOR,
    NICARAGUA,
    CUBA,
    DOMINICAN_REPUBLIC,
    PUERTO_RICO,
    // North America
    UNITED_STATES,
    CANADA,
    // Europe
    SPAIN,
    GERMANY,
    FRANCE,
    ITALY,
    UNITED_KINGDOM,
    PORTUGAL,
    NETHERLANDS,
    BELGIUM,
    SWITZERLAND,
    SWEDEN,
    NORWAY,
    DENMARK,
    POLAND,
    RUSSIA,
    UKRAINE,
    AUSTRIA,
    IRELAND,
    GREECE,
    TURKEY,
    // Asia
    CHINA,
    JAPAN,
    SOUTH_KOREA,
    INDIA,
    THAILAND,
    VIETNAM,
    INDONESIA,
    PHILIPPINES,
    MALAYSIA,
    SINGAPORE,
    ISRAEL,
    SAUDI_ARABIA,
    UNITED_ARAB_EMIRATES,
    // Oceania
    AUSTRALIA,
    NEW_ZEALAND,
    // Africa
    SOUTH_AFRICA,
    NIGERIA,
    EGYPT,
    MOROCCO,
    OTHER
}
