package com.daboerp.gestion.domain.entity;

import com.daboerp.gestion.domain.valueobject.BedId;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import java.util.Objects;

/**
 * Bed entity - represents an individual bed within a room.
 */
@Getter
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Bed {
    
    @EqualsAndHashCode.Include
    private final BedId id;
    private final Integer bedNumber;
    @Setter
    private Room room;
    
    private Bed(BedId id, Integer bedNumber, Room room, boolean allowNullRoom) {
        this.id = Objects.requireNonNull(id, "Bed ID cannot be null");
        this.bedNumber = Objects.requireNonNull(bedNumber, "Bed number cannot be null");
        if (!allowNullRoom) {
            this.room = Objects.requireNonNull(room, "Room cannot be null");
        } else {
            this.room = room;
        }
        
        if (bedNumber <= 0) {
            throw new IllegalArgumentException("Bed number must be positive");
        }
    }
    
    public static Bed create(Integer bedNumber, Room room) {
        BedId id = BedId.generate();
        return new Bed(id, bedNumber, room, false);
    }
    
    public static Bed reconstitute(BedId id, Integer bedNumber, Room room) {
        return new Bed(id, bedNumber, room, true);
    }
    
    
    // Getters, equals, and hashCode are generated by Lombok
}
