package com.daboerp.gestion.domain.entity;

import lombok.EqualsAndHashCode;
import lombok.Getter;

import java.util.Objects;
import java.util.UUID;

/**
 * Notes entity - structured notes with severity classification.
 * Composed by Guest.
 */
@Getter
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Notes {
    
    @EqualsAndHashCode.Include
    private final String id;
    private final String text;
    private final LevelNote level;
    
    private Notes(String id, String text, LevelNote level) {
        this.id = Objects.requireNonNull(id, "Notes ID cannot be null");
        this.text = Objects.requireNonNull(text, "Text cannot be null");
        this.level = Objects.requireNonNull(level, "Level cannot be null");
    }
    
    public static Notes create(String text, LevelNote level) {
        return new Notes(UUID.randomUUID().toString(), text, level);
    }
    
    public static Notes reconstitute(String id, String text, LevelNote level) {
        return new Notes(id, text, level);
    }
    
    // Getters, equals, and hashCode are generated by Lombok
}
