package com.daboerp.gestion.domain.entity;

import lombok.EqualsAndHashCode;
import lombok.Getter;

import java.util.Objects;
import java.util.UUID;

/**
 * ReservationStatus entity - tracks the current state of a reservation.
 */
@Getter
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class ReservationStatus {
    
    @EqualsAndHashCode.Include
    private final String id;
    private final StatusType statusType;
    private final String note;
    
    private ReservationStatus(String id, StatusType statusType, String note) {
        this.id = Objects.requireNonNull(id, "Status ID cannot be null");
        this.statusType = Objects.requireNonNull(statusType, "Status type cannot be null");
        this.note = note;
    }
    
    public static ReservationStatus create(StatusType statusType, String note) {
        return new ReservationStatus(UUID.randomUUID().toString(), statusType, note);
    }
    
    public static ReservationStatus reconstitute(String id, StatusType statusType, String note) {
        return new ReservationStatus(id, statusType, note);
    }
    
    // Getters, equals, and hashCode are generated by Lombok
}
