package com.daboerp.gestion.domain.entity;

import com.daboerp.gestion.domain.valueobject.RoomTypeId;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * RoomType entity - defines category and pricing of rooms.
 * Composed by Room.
 */
@Getter
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class RoomType {
    
    @EqualsAndHashCode.Include
    private final RoomTypeId id;
    @Setter
    private String name;
    @Setter
    private String description;
    @Setter
    private int maxOccupancy;
    @Setter
    private BigDecimal basePrice;
    
    private RoomType(RoomTypeId id, String name, String description, int maxOccupancy, BigDecimal basePrice) {
        this.id = Objects.requireNonNull(id, "Room type ID cannot be null");
        this.name = Objects.requireNonNull(name, "Name cannot be null");
        this.description = description;
        this.maxOccupancy = maxOccupancy;
        this.basePrice = Objects.requireNonNull(basePrice, "Base price cannot be null");
        
        validateMaxOccupancy(maxOccupancy);
        validateBasePrice(basePrice);
    }
    
    public static RoomType create(String name, String description, int maxOccupancy, BigDecimal basePrice) {
        RoomTypeId id = RoomTypeId.generate();
        return new RoomType(id, name, description, maxOccupancy, basePrice);
    }
    
    public static RoomType reconstitute(RoomTypeId id, String name, String description, 
                                       int maxOccupancy, BigDecimal basePrice) {
        return new RoomType(id, name, description, maxOccupancy, basePrice);
    }
    
    public void updatePricing(BigDecimal newBasePrice) {
        validateBasePrice(newBasePrice);
        this.basePrice = newBasePrice;
    }
    
    public void updateDetails(String name, String description, int maxOccupancy) {
        Objects.requireNonNull(name, "Name cannot be null");
        validateMaxOccupancy(maxOccupancy);
        this.name = name;
        this.description = description;
        this.maxOccupancy = maxOccupancy;
    }
    
    private void validateMaxOccupancy(int maxOccupancy) {
        if (maxOccupancy <= 0) {
            throw new IllegalArgumentException("Max occupancy must be positive");
        }
    }
    
    private void validateBasePrice(BigDecimal basePrice) {
        if (basePrice.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Base price must be positive");
        }
    }
    
    // Getters, equals, and hashCode are generated by Lombok
}
